# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package
on:
  push: 
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: we are checking the code...
        uses: actions/checkout@v2 
        
      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'  

      - name: Build docker image
        run: docker build -t avdhut2002/addtwonumbers:latest -f Dockerfile .

      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
         username: ${{secrets.USER_NAME}}
         password: ${{secrets.USER_PASSWORD}}

      - name: Push docker image in docker hub
        run: docker push avdhut2002/addtwonumbers:latest

   
   
